### ISSUE TITLE
error

### ISSUE THREAD

**Issue by prasadajith** [mludowise/Sketch-HTML-Export#4]
while trying to export the following error is shown

{
    column = 46;
    line = 42;
    sourceURL = "/Users/mac/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Sketch Html Export/HTML.sketchplugin/Contents/Sketch/html.cocoascript";
}

**Comment by prasadajith** [comment]
The same error for version 0.1 as well...

I am using sketch 45.1

**Comment by mludowise** [comment]
Thank you for catching this. It should be fixed now.

**Comment by prasadajith** [comment]
It still does not work with sketch 45.1

the error message has stopped showing, but the option window does not appear, and does not export from sketch 45.1
